Started by user [8mha:////4CDaLzao4A67utYR77ls98WC8cTIZkXIASznBGiVkvolAAAAmR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAz2EgZe/dLi1CL9rNS87My8YgDGtiJjwgAAAA==[0mJenkins
Running as SYSTEM
Building in workspace /var/jenkins_home/workspace/ansible-test
[8mha:////4JwlLCpenXligcDX2iDKKqZGgMTSTCI+JDAKK9MvdvfAAAAAqx+LCAAAAAAAAP9b85aBtbiIQSujNKU4P0+vIKc0PTOvWC8xrzgzOT8nv0gvMbkkEyjhCKb88ktSdwVsu2efuqidiYHRh4EDIu2ZUsIg5JOVWJaon5OYl64fXFKUmZduXVHEIAU1ODk/rzg/J1XPGUKDDGKAAEYmBoaKghIGFTPzlFTzJMMk3URTA0tdkxRzA91EM0MTXSMDc7M08yQzY0MjUwCLViqyrwAAAA==[0m[ansible-test] $ ansible-playbook /var/jenkins_home/ansible/play.yml -i /var/jenkins_home/ansible/hosts -f 5 -e "MSG='HELLO WORLD'"
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.exceptions import InvalidSignature

PLAY [test1] *******************************************************************

TASK [Gathering Facts] *********************************************************
[0;32mok: [test1][0m

TASK [shell] *******************************************************************
[0;33mchanged: [test1][0m

TASK [debug] *******************************************************************
[0;32mok: [test1] => {[0m
[0;32m    "msg": "HELLO WORLD"[0m
[0;32m}[0m

PLAY RECAP *********************************************************************
[0;33mtest1[0m                      : [0;32mok=3   [0m [0;33mchanged=1   [0m unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Finished: SUCCESS
